version: '2.2'

services: 
  salt-master:
    build:
      context: ./master
      dockerfile: Dockerfile
  salt-minion:
    build:
      context: ./minion
      dockerfile: Dockerfile
    depends_on:
      - salt-master
    scale: 2
