version: '2.2'

services: 
  salt-master:
    container_name: salt-master
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    build:
      context: ./master
      dockerfile: Dockerfile
      args:
        - MASTER_ID=salt-master
  salt-minion:
    container_name: salt-minion
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    build:
      context: ./minion
      dockerfile: Dockerfile
      args:
        - MINION_ID=salt-minion
    depends_on:
      - salt-master
