version: '2.2'

services: 
  salt-master:
    build:
      context: ./master
      dockerfile: Dockerfile
      args:
        - MASTER_ID=salt-master
  salt-minion:
    build:
      context: ./minion
      dockerfile: Dockerfile
      args:
        - MINION_ID=salt-minion
    depends_on:
      - salt-master
